spring:
    datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

jwt:
    accessToken:
        secretKey: ${ACCESS_TOKEN_SECRET}
        expirationMinutes: 15
    refreshToken:
        secretKey: ${REFRESH_TOKEN_SECRET}
        expirationMinutes: 20160
